### ISSUE TITLE
v5.1.18 empty.html accidentally includes a splash screen

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/build.jermolene.github.io#5]
The v5.1.18 version of https://tiddlywiki.com/empty.html includes a splash screen, even though it doesn't include the raw markup tiddler that is responsible for it.

The problem is that empty.html [is constructed](https://github.com/Jermolene/build.jermolene.github.io/blob/master/bld.sh#L76) from the main `editions/tw5.com` wiki, rather than from the `editions/empty` edition. The former includes a splash screen tiddler that is included when saving the HTML file, even though that same splash screen tiddler is excluded by the save filter employed when saving the `empty.html` file.

**Comment by jehendricks** [comment]
Just downloaded v5.1.19 empty and it still contains the main wiki splash screen.  Release notes for v5.1.19 indicated this has been fixed and directs to this issue.

**Comment by Jermolene** [comment]
Thanks @jehendricks this is kind of a new bug; you'll see that the empty version at https://tiddlywiki.com/empty.html doesn't include the splash screen but the version you get when you click the "download" button in "GettingStarted" on https://tiddlywiki.com/ does in fact include the splash screen. I'll create a new ticket.

**Comment by jehendricks** [comment]
Ah, got it.  I’ll download from empty directly then in the mean time.  Thanks for the hard work!

Jim Hendricks
Sr. Software Developer, Mobile Team
IT Development

(434) 592-4815

[id:image001.jpg@01D3A965.A7717CE0]

Liberty University  |  Training Champions for Christ since 1971
